// Local brand list for the Add Product autocomplete. Not a live product
// database — no external "beauty products API" is wired up (none was
// available to integrate), so this only suggests brand names; product
// name, category and time-of-day are still entered manually. Typing a
// name that isn't on this list just adds it as free text, same as before.
export const BRANDS = [
  '25 Pskynn',
  'Abib',
  'Acne beauty',
  'Acwell',
  'Anua',
  'Arami',
  'Avène',
  'Axis-Y',
  'Beauty of Joseon',
  'Bioderma',
  'Biore',
  'Bolden',
  'Bondi Sands',
  'Cerave',
  'Cetaphil',
  'Clinique',
  'Cosrx',
  'Dang',
  'Differin',
  'Dove',
  'Dr. Althea',
  'Dr. Teals',
  'E45',
  'Ebunderma',
  'EOS',
  'Estée Lauder',
  'Eucerin',
  'Ezanic',
  'Face Facts',
  'Frudia',
  'Garnier',
  'Good Molecules',
  'Hada Labo',
  'Haru Haru Wonder',
  'House of Coco',
  'Illiyoon',
  "I'm From",
  'Innisfree',
  'Isi Naturals',
  'Isispharma',
  'Isntree',
  'Jumiso',
  'Kiehls',
  'Klairs',
  'Kose',
  'La Roche Posay',
  "L'Oreal",
  'Mai Skin',
  'Medix 5.5',
  'Medicube',
  'Mesoestetic',
  'Missha',
  'Mixsoon',
  'Msmetics',
  'Naturium',
  'Nineless',
  'Nivea',
  'Numbuzin',
  'Obagi',
  'Olay',
  "Paula's Choice",
  'Panoxyl',
  'Purito',
  'Pyunkang Yul',
  'Rejuva',
  'Replenix',
  'Revox',
  'Round Lab',
  'Sachi Skin',
  'Seoul 1988',
  'Sesderma',
  'Simple',
  'Skin 1004',
  'Skin Aqua',
  'Skin by Zaron',
  'Skinceuticals',
  'Skinscience',
  'Soapy Suds',
  'Soibi Botanicals',
  'Some by Mi',
  'Soonjung',
  'St. Ives',
  'Sufte skin',
  'The Inkey List',
  'The Ordinary',
  'Tiam',
  'Timeless',
  'Tirtir',
  'Tocobo',
  'Tonymoly',
  'Topicals',
  'Topicrem',
  'Torriden',
  'Touch',
  'Tree Hut',
  'Uncover',
  'Urban Skin Rx',
  'Uriage',
  'Vaseline',
  'Vt Cosmetics',
]
