// Products cataloged from the Nigerian/African market ingredient tracker
// spreadsheet, with real INCI-style ingredient lists so detectActive() can
// work from actual actives rather than guessing from the product name.
// usageTime (AM/PM/BOTH) comes straight from the sheet, not guessed.

export const NIGERIAN_PRODUCTS = [
  { brand: 'Bolden', name: 'Dark Spots Fix', category: 'serum', ingredients: 'Kojic acid, Azelaic Acid, Niacinamide, Alpha Arbutin', usageTime: 'BOTH' },
  { brand: 'Bolden', name: 'Nighttime Repair Serum', category: 'serum', ingredients: '10% Glycolic acid', usageTime: 'PM' },
  { brand: 'Bolden', name: 'F-Hydra Moisturizer', category: 'moisturizer', ingredients: 'Ceramides, peptides, Vitamin F', usageTime: 'BOTH' },
  { brand: 'Bolden', name: 'Sunscreen Serum', category: 'sunscreen', ingredients: 'UV filters, skincare/antioxidant ingredients', usageTime: 'BOTH' },
  { brand: 'Bolden', name: 'Skin Clarifying Cleanser', category: 'cleanser', ingredients: '', usageTime: 'BOTH' },
  { brand: 'Sufte Skin', name: 'Dark Spots Correcting Face Serum', category: 'serum', ingredients: 'Azelaic acid, N-Acetyly Glucosamine, Tranexamic acid, Alpha Arbutin', usageTime: 'BOTH' },
  { brand: 'Sufte Skin', name: 'Bright Boost Barrier Face Creme', category: 'moisturizer', ingredients: 'D- Pathenol, Allantoin, Salix Alba Bark Extract, Butylene Glycol, Carbomer, Polysorbate 20, Palmitoyl Tripeptude-1, Palmitoyl Tetrapeptide-7,', usageTime: 'BOTH' },
  { brand: 'Sufte Skin', name: 'Regen Exfoliator', category: 'exfoliant', ingredients: 'Lactic Acid, Salicylic acid, Mandelic acid, Malic acid', usageTime: 'PM' },
  { brand: 'Ebun Derma', name: 'Daily Acne Wash', category: 'cleanser', ingredients: 'Glycolic Acid, Salicylic Acid PLUS, Lactic Acid,', usageTime: 'BOTH' },
  { brand: 'Ebun Derma', name: 'Fader', category: 'serum', ingredients: 'Kojic Acid, Alpha Arbutin, Ascorbyl Glucoside, Niacinamide PC, Tranexamic Acid', usageTime: 'PM' },
  { brand: 'Ebun Derma', name: 'Unclog', category: 'exfoliant', ingredients: 'Salicylic Acid', usageTime: 'PM' },
  { brand: 'La Roche Posay', name: 'Mela B3 Dark Spot Serum', category: 'serum', ingredients: 'Niacinamide, Melasyl™, LHA, Retinyl Palmitate', usageTime: 'BOTH' },
  { brand: 'La Roche Posay', name: 'Mela B3 Facial Gel Cleanser', category: 'cleanser', ingredients: 'Niacinamide, Melasyl™, Gluconolactone', usageTime: 'BOTH' },
  { brand: 'La Roche Posay', name: 'Effaclar Duo (+)', category: 'serum', ingredients: 'Niacinamide, LHA, Salicylic Acid', usageTime: 'PM' },
  { brand: 'La Roche Posay', name: 'Effaclar Micro-Peeling Purifying Gel', category: 'cleanser', ingredients: 'Salicylic Acid, LHA', usageTime: 'BOTH' },
  { brand: 'La Roche Posay', name: 'Effaclar Medicated Gel Cleanser', category: 'cleanser', ingredients: 'Salicylic Acid', usageTime: 'BOTH' },
  { brand: 'La Roche Posay', name: 'Effaclar Ultra Concentrate Serum', category: 'serum', ingredients: 'Salicylic Acid, Glycolic Acid, LHA', usageTime: 'PM' },
  { brand: 'La Roche Posay', name: 'Retinol B3 Serum', category: 'serum', ingredients: 'Retinol, Niacinamide', usageTime: 'PM' },
  { brand: 'La Roche Posay', name: 'Hyalu B5 Serum', category: 'serum', ingredients: 'Hyaluronic Acid, Panthenol, Madecassoside', usageTime: 'BOTH' },
  { brand: 'La Roche Posay', name: 'Pure Vitamin C10 Serum', category: 'serum', ingredients: 'Vitamin C, Salicylic Acid', usageTime: 'AM' },
  { brand: 'La Roche Posay', name: 'Cicaplast Baume B5+', category: 'moisturizer', ingredients: 'Panthenol, Madecassoside', usageTime: 'BOTH' },
  { brand: 'La Roche Posay', name: 'Anthelios UVMune 400 SPF50+', category: 'sunscreen', ingredients: 'UV filters', usageTime: 'AM' },
  { brand: 'La Roche Posay', name: 'Mela B3 UV Daily Moisturizer SPF30', category: 'sunscreen', ingredients: 'Niacinamide, Melasyl™, LHA', usageTime: 'AM' },
  { brand: 'Cerave', name: 'Foaming Facial Cleanser', category: 'cleanser', ingredients: 'Ceramides, Niacinamide', usageTime: 'BOTH' },
  { brand: 'Cerave', name: 'Hydrating Facial Cleanser', category: 'cleanser', ingredients: 'Ceramides, Hyaluronic Acid', usageTime: 'BOTH' },
  { brand: 'Cerave', name: 'SA Smoothing Cleanser', category: 'cleanser', ingredients: 'Salicylic Acid, Ceramides', usageTime: 'BOTH' },
  { brand: 'Cerave', name: 'Acne Control Cleanser', category: 'cleanser', ingredients: 'Salicylic Acid, Niacinamide', usageTime: 'BOTH' },
  { brand: 'Cerave', name: 'Resurfacing Retinol Serum', category: 'serum', ingredients: 'Retinol, Niacinamide, Ceramides', usageTime: 'PM' },
  { brand: 'Cerave', name: 'Skin Renewing Retinol Serum', category: 'serum', ingredients: 'Retinol, Ceramides', usageTime: 'PM' },
  { brand: 'Cerave', name: 'Vitamin C Serum', category: 'serum', ingredients: 'Vitamin C, Ceramides', usageTime: 'AM' },
  { brand: 'Cerave', name: 'PM Facial Moisturizing Lotion', category: 'moisturizer', ingredients: 'Ceramides, Niacinamide, Hyaluronic Acid', usageTime: 'PM' },
  { brand: 'Cerave', name: 'AM Moisturizing Lotion', category: 'moisturizer', ingredients: 'Ceramides, Hyaluronic Acid', usageTime: 'AM' },
  { brand: 'The Ordinary', name: 'Niacinamide 10% + Zinc 1%', category: 'serum', ingredients: 'Niacinamide, Zinc PCA', usageTime: 'BOTH' },
  { brand: 'The Ordinary', name: 'Azelaic Acid Suspension 10%', category: 'serum', ingredients: 'Azelaic Acid', usageTime: 'BOTH' },
  { brand: 'The Ordinary', name: 'Alpha Arbutin 2% + HA', category: 'serum', ingredients: 'Alpha Arbutin, Hyaluronic Acid', usageTime: 'AM' },
  { brand: 'The Ordinary', name: 'Ascorbic Acid 8% + Alpha Arbutin 2%', category: 'serum', ingredients: 'Vitamin C, Alpha Arbutin', usageTime: 'AM' },
  { brand: 'The Ordinary', name: 'Glycolic Acid 7% Exfoliating Toner', category: 'exfoliant', ingredients: 'Glycolic Acid', usageTime: 'PM' },
  { brand: 'The Ordinary', name: 'Lactic Acid 10% + HA', category: 'serum', ingredients: 'Lactic Acid', usageTime: 'PM' },
  { brand: 'The Ordinary', name: 'Mandelic Acid 10% + HA', category: 'serum', ingredients: 'Mandelic Acid', usageTime: 'PM' },
  { brand: 'The Ordinary', name: 'Retinol 0.2% in Squalane', category: 'serum', ingredients: 'Retinol', usageTime: 'PM' },
  { brand: 'The Ordinary', name: 'Retinol 0.5% in Squalane', category: 'serum', ingredients: 'Retinol', usageTime: 'PM' },
  { brand: 'The Ordinary', name: 'Retinol 1% in Squalane', category: 'serum', ingredients: 'Retinol', usageTime: 'PM' },
  { brand: 'The Ordinary', name: 'Granactive Retinoid 2% Emulsion', category: 'serum', ingredients: 'Hydroxypinacolone Retinoate', usageTime: 'PM' },
  { brand: 'The Ordinary', name: 'Multi-Peptide + HA Serum', category: 'serum', ingredients: 'Peptides', usageTime: 'BOTH' },
  { brand: 'Cosrx', name: 'Advanced Snail 96 Mucin Power Essence', category: 'essence', ingredients: 'Snail Mucin', usageTime: 'BOTH' },
  { brand: 'Cosrx', name: 'Advanced Snail 92 All In One Cream', category: 'essence', ingredients: 'Snail Mucin', usageTime: 'BOTH' },
  { brand: 'Cosrx', name: 'BHA Blackhead Power Liquid', category: 'exfoliant', ingredients: 'Betaine Salicylate', usageTime: 'BOTH' },
  { brand: 'Cosrx', name: 'AHA 7 Whitehead Power Liquid', category: 'exfoliant', ingredients: 'Glycolic Acid', usageTime: 'BOTH' },
  { brand: 'Cosrx', name: 'The 6 Peptide Skin Booster', category: 'essence', ingredients: 'Peptides, Niacinamide', usageTime: 'BOTH' },
  { brand: 'Cosrx', name: 'Niacinamide 15 Serum', category: 'serum', ingredients: 'Niacinamide', usageTime: 'BOTH' },
  { brand: 'Cosrx', name: 'The Vitamin C 23 Serum', category: 'serum', ingredients: 'Vitamin C', usageTime: 'AM' },
  { brand: 'Cosrx', name: 'The Vitamin C 13 Serum', category: 'serum', ingredients: 'Vitamin C', usageTime: 'AM' },
  { brand: 'Cosrx', name: 'Retinol 0.1 Cream', category: 'moisturizer', ingredients: 'Retinol', usageTime: 'PM' },
  { brand: 'Cosrx', name: 'Retinol 0.5 Oil', category: 'serum', ingredients: 'Retinol', usageTime: 'PM' },
  { brand: 'Cosrx', name: 'Propolis Light Ampoule', category: 'serum', ingredients: 'Propolis', usageTime: 'BOTH' },
  { brand: 'Beauty of Joseon', name: 'Glow Serum: Propolis + Niacinamide', category: 'serum', ingredients: 'Propolis, Niacinamide', usageTime: 'BOTH' },
  { brand: 'Beauty of Joseon', name: 'Glow Deep Serum: Rice + Alpha-Arbutin', category: 'serum', ingredients: 'Alpha Arbutin, Rice Extract', usageTime: 'BOTH' },
  { brand: 'Beauty of Joseon', name: 'Revive Serum: Ginseng + Snail Mucin', category: 'serum', ingredients: 'Ginseng, Snail Mucin', usageTime: 'BOTH' },
  { brand: 'Beauty of Joseon', name: 'Ginseng Essence Water', category: 'toner', ingredients: 'Ginseng, Niacinamide', usageTime: 'BOTH' },
  { brand: 'Beauty of Joseon', name: 'Relief Sun SPF50+', category: 'sunscreen', ingredients: 'Rice Extract, Probiotics, UV filters', usageTime: 'AM' },
  { brand: 'Eucerin', name: 'Anti-Pigment Dual Serum', category: 'serum', ingredients: 'Thiamidol, Hyaluronic Acid', usageTime: 'BOTH' },
  { brand: 'Eucerin', name: 'Anti-Pigment Spot Corrector', category: 'serum', ingredients: 'Thiamidol', usageTime: 'BOTH' },
  { brand: 'Eucerin', name: 'Anti-Pigment Day SPF30', category: 'sunscreen', ingredients: 'Thiamidol, UV filters', usageTime: 'AM' },
  { brand: 'Paula\'s Choice', name: 'Skin Perfecting 2% BHA Liquid', category: 'serum', ingredients: 'Salicylic Acid', usageTime: 'PM' },
  { brand: 'Paula\'s Choice', name: '10% Azelaic Acid Booster', category: 'serum', ingredients: 'Azelaic Acid, Salicylic Acid', usageTime: 'BOTH' },
  { brand: 'Paula\'s Choice', name: '10% Niacinamide Booster', category: 'serum', ingredients: 'Niacinamide', usageTime: 'BOTH' },
  { brand: 'Paula\'s Choice', name: 'Clinical 1% Retinol Treatment', category: 'serum', ingredients: 'Retinol', usageTime: 'PM' },
  { brand: 'Paula\'s Choice', name: '0.3% Retinol + 2% Bakuchiol', category: 'serum', ingredients: 'Retinol, Bakuchiol', usageTime: 'PM' },
  { brand: 'Paula\'s Choice', name: 'C15 Super Booster', category: 'serum', ingredients: 'Vitamin C, Vitamin E, Ferulic Acid', usageTime: 'BOTH' },
  { brand: 'Paula\'s Choice', name: '25% AHA + 2% BHA Exfoliant Peel', category: 'toner', ingredients: 'AHA, BHA', usageTime: 'PM' },
  { brand: 'SKIN1004', name: 'Madagascar Centella Ampoule', category: 'serum', ingredients: 'Centella Asiatica', usageTime: 'BOTH' },
  { brand: 'SKIN1004', name: 'Tone Brightening Capsule Ampoule', category: 'serum', ingredients: 'Niacinamide, Tranexamic Acid, Madecassoside', usageTime: 'BOTH' },
  { brand: 'SKIN1004', name: 'Centella Toning Toner', category: 'toner', ingredients: 'PHA, Centella', usageTime: 'BOTH' },
  { brand: 'SKIN1004', name: 'Centella Poremizing Fresh Ampoule', category: 'serum', ingredients: 'Centella, Niacinamide', usageTime: 'BOTH' },
  { brand: 'SKIN1004', name: 'Hyalu-Cica Water-Fit Sun Serum SPF50+', category: 'sunscreen', ingredients: 'Hyaluronic Acid, Centella, UV filters', usageTime: 'AM' },
  { brand: 'SKIN1004', name: 'Hyalu-Cica First Ampoule', category: 'serum', ingredients: 'Hyaluronic Acid, Centella', usageTime: 'BOTH' },
  { brand: 'SKIN1004', name: 'Probio-Cica Intensive Ampoule', category: 'serum', ingredients: 'Fermented Centella, Ceramides', usageTime: 'BOTH' },
  { brand: 'SKIN1004', name: 'Probio-Cica Enrich Cream', category: 'moisturizer', ingredients: 'Ceramides, Fermented Centella', usageTime: 'BOTH' },
  { brand: 'Anua', name: 'Heartleaf 77% Soothing Toner', category: 'toner', ingredients: 'Heartleaf', usageTime: 'BOTH' },
  { brand: 'Anua', name: 'Niacinamide 10% + TXA 4% Serum', category: 'serum', ingredients: 'Niacinamide, Tranexamic Acid', usageTime: 'BOTH' },
  { brand: 'Anua', name: 'Azelaic Acid 10 Hyaluron Redness Soothing Serum', category: 'serum', ingredients: 'Azelaic Acid', usageTime: 'BOTH' },
  { brand: 'Anua', name: 'Peach 77% Niacin Enriched Cream', category: 'serum', ingredients: 'Niacinamide, Peach Extract', usageTime: 'BOTH' },
  { brand: 'Anua', name: 'Heartleaf Pore Control Cleansing Oil', category: 'cleanser', ingredients: 'Heartleaf', usageTime: 'PM' },
  { brand: 'Anua', name: 'Heartleaf Quercetinol Pore Deep Cleansing Foam', category: 'cleanser', ingredients: 'Heartleaf, Quercetinol', usageTime: 'BOTH' },
  { brand: 'Naturium', name: 'Niacinamide Serum 12% + Zinc 2%', category: 'serum', ingredients: 'Niacinamide, Zinc', usageTime: 'BOTH' },
  { brand: 'Naturium', name: 'Azelaic Topical Acid 10%', category: 'serum', ingredients: 'Azelaic Acid', usageTime: 'BOTH' },
  { brand: 'Naturium', name: 'Tranexamic Topical Acid 5%', category: 'serum', ingredients: 'Tranexamic Acid', usageTime: 'BOTH' },
  { brand: 'Naturium', name: 'Vitamin C Complex Serum', category: 'serum', ingredients: 'Vitamin C', usageTime: 'AM' },
  { brand: 'Naturium', name: 'BHA Liquid Exfoliant 2%', category: 'exfoliant', ingredients: 'Salicylic Acid', usageTime: 'PM' },
  { brand: 'Naturium', name: 'Glycolic Acid Resurfacing Gel 10%', category: 'exfoliant', ingredients: 'Glycolic Acid', usageTime: 'PM' },
  { brand: 'Naturium', name: 'Multi-Peptide Advanced Serum', category: 'serum', ingredients: 'Peptides', usageTime: 'BOTH' },
  { brand: 'Good Molecules', name: 'Niacinamide Serum', category: 'serum', ingredients: 'Niacinamide', usageTime: 'BOTH' },
  { brand: 'Good Molecules', name: 'Discoloration Correcting Serum', category: 'serum', ingredients: 'Tranexamic Acid derivative', usageTime: 'BOTH' },
  { brand: 'Good Molecules', name: 'Daily Essentials Brightening Serum', category: 'serum', ingredients: 'Vitamin C derivative', usageTime: 'AM' },
  { brand: 'Good Molecules', name: 'Overnight Exfoliating Treatment', category: 'exfoliant', ingredients: 'AHA, BHA', usageTime: 'PM' },
  { brand: 'Good Molecules', name: 'Gentle Retinol Cream', category: 'treatment', ingredients: 'Retinol', usageTime: 'PM' },
  { brand: 'Good Molecules', name: 'Yerba Mate Wake Up Eye Gel', category: 'moisturizer', ingredients: 'Caffeine, Yerba Mate', usageTime: 'BOTH' },
  { brand: 'Good Molecules', name: 'Hyaluronic Acid Serum', category: 'serum', ingredients: 'Hyaluronic Acid', usageTime: 'BOTH' },
  { brand: 'Good Molecules', name: 'BHA Clarify Gel Cream', category: 'treatment', ingredients: 'Salicylic Acid', usageTime: 'PM' },
  { brand: 'Topicals', name: 'Faded Serum', category: 'serum', ingredients: 'Tranexamic Acid, Azelaic Acid, Niacinamide, Kojic Acid', usageTime: 'BOTH' },
  { brand: 'Topicals', name: 'Like Butter Mask', category: 'mask', ingredients: 'Colloidal Oatmeal, Ceramides', usageTime: 'AM' },
  { brand: 'Topicals', name: 'Faded Brightening & Clearing Mist', category: 'toner', ingredients: 'Tranexamic Acid, Niacinamide', usageTime: 'BOTH' },
  { brand: 'The Inkey List', name: 'Niacinamide Serum', category: 'serum', ingredients: 'Niacinamide', usageTime: 'BOTH' },
  { brand: 'The Inkey List', name: 'Succinic Acid Acne Treatment', category: 'serum', ingredients: 'Succinic Acid, Salicylic Acid', usageTime: 'PM' },
  { brand: 'The Inkey List', name: 'Beta Hydroxy Acid', category: 'serum', ingredients: 'Salicylic Acid', usageTime: 'PM' },
  { brand: 'The Inkey List', name: 'PHA Toner', category: 'exfoliant', ingredients: 'PHA', usageTime: 'PM' },
  { brand: 'The Inkey List', name: 'Retinol Serum', category: 'serum', ingredients: 'Retinol', usageTime: 'PM' },
  { brand: 'The Inkey List', name: 'Tranexamic Acid Serum', category: 'serum', ingredients: 'Tranexamic Acid', usageTime: 'BOTH' },
  { brand: 'The Inkey List', name: 'Azelaic Acid Serum', category: 'serum', ingredients: 'Azelaic Acid', usageTime: 'BOTH' },
  { brand: 'The Inkey List', name: 'Vitamin C Serum', category: 'serum', ingredients: 'Vitamin C', usageTime: 'BOTH' },
  { brand: 'The Inkey List', name: 'Hyaluronic Acid Serum', category: 'serum', ingredients: 'Hyaluronic Acid', usageTime: 'BOTH' },
  { brand: 'The Inkey List', name: 'Peptide Moisturizer', category: 'serum', ingredients: 'Peptides', usageTime: 'BOTH' },
  { brand: 'PanOxyl', name: 'Acne Foaming Wash 4%', category: 'cleanser', ingredients: 'Benzoyl Peroxide', usageTime: 'BOTH' },
  { brand: 'Differin', name: 'Adapalene Gel 0.1%', category: 'treatment', ingredients: 'Adapalene', usageTime: 'PM' },
  { brand: 'Murad', name: 'Rapid Relief Acne Spot Treatment', category: 'serum', ingredients: 'Salicylic Acid', usageTime: 'PM' },
  { brand: 'Murad', name: 'Rapid Dark Spot Correcting Serum', category: 'serum', ingredients: 'Resorcinol derivative', usageTime: 'BOTH' },
  { brand: 'SkinCeuticals', name: 'C E Ferulic', category: 'serum', ingredients: 'Vitamin C, Vitamin E, Ferulic Acid', usageTime: 'AM' },
  { brand: 'SkinCeuticals', name: 'Blemish + Age Defense', category: 'serum', ingredients: 'Salicylic Acid, Dioic Acid', usageTime: 'PM' },
  { brand: 'Medik8', name: 'Crystal Retinal', category: 'serum', ingredients: 'Retinal', usageTime: 'PM' },
  { brand: 'Urban Skin Rx', name: 'Even Tone Cleansing Bar', category: 'cleanser', ingredients: 'Kojic Acid, Azelaic Acid', usageTime: 'BOTH' },
  { brand: 'Urban Skin Rx', name: 'Even Tone Super Glow Serum', category: 'cleanser', ingredients: 'Vitamin C, Niacinamide', usageTime: 'AM' },
  { brand: 'Glow Recipe', name: 'Watermelon Glow Niacinamide Dew Drops', category: 'serum', ingredients: 'Niacinamide', usageTime: 'BOTH' },
  { brand: 'Glow Recipe', name: 'PHA + BHA Pore-Tight Toner', category: 'exfoliant', ingredients: 'PHA, BHA', usageTime: 'PM' },
  { brand: 'Byoma', name: 'Brighten & Balance Serum', category: 'serum', ingredients: 'Niacinamide, Azelaic Acid', usageTime: 'BOTH' },
  { brand: 'Byoma', name: 'Balancing Face Mist', category: 'toner', ingredients: 'Ceramides, Niacinamide', usageTime: 'BOTH' },
  { brand: 'Bubble', name: 'Level Up Gel Moisturizer', category: 'moisturizer', ingredients: 'Hyaluronic Acid', usageTime: 'BOTH' },
  { brand: 'Minimalist', name: 'Retinol 0.3%', category: 'serum', ingredients: 'Retinol', usageTime: 'PM' },
  { brand: 'Hada Labo', name: 'Gokujyun Hyaluronic Acid Lotion', category: 'moisturizer', ingredients: 'Hyaluronic Acid', usageTime: 'BOTH' },
  { brand: 'Hada Labo', name: 'Shirojyun Premium Lotion', category: 'moisturizer', ingredients: 'Tranexamic Acid', usageTime: 'BOTH' },
  { brand: 'Isntree', name: 'Chestnut BHA 2% Clear Liquid', category: 'exfoliant', ingredients: 'Salicylic Acid', usageTime: 'PM' },
  { brand: 'Isntree', name: 'Hyper Niacinamide 20 Serum', category: 'serum', ingredients: 'Niacinamide', usageTime: 'BOTH' },
  { brand: 'Round Lab', name: 'Birch Juice Moisturizing Sun Cream', category: 'moisturizer', ingredients: 'UV filters, Birch Sap', usageTime: 'AM' },
  { brand: 'Haruharu Wonder', name: 'Black Rice Hyaluronic Toner', category: 'toner', ingredients: 'Hyaluronic Acid', usageTime: 'BOTH' },
  { brand: 'Purito', name: 'Centella Unscented Serum', category: 'serum', ingredients: 'Centella, Niacinamide', usageTime: 'BOTH' },
  { brand: 'Axis-Y', name: 'Dark Spot Correcting Glow Serum', category: 'serum', ingredients: 'Niacinamide', usageTime: 'BOTH' },
  { brand: 'Some By Mi', name: 'AHA BHA PHA 30 Days Miracle Toner', category: 'exfoliant', ingredients: 'AHA, BHA, PHA', usageTime: 'PM' },
  { brand: 'Tiam', name: 'B3 Source Serum', category: 'serum', ingredients: 'Niacinamide', usageTime: 'BOTH' },
  { brand: 'Tiam', name: 'Pore Minimizing 21 Serum', category: 'serum', ingredients: 'Niacinamide', usageTime: 'BOTH' },
  { brand: 'Numbuzin', name: 'No.5+ Vitamin Concentrated Serum', category: 'serum', ingredients: 'Vitamin C derivatives, Niacinamide', usageTime: 'AM' },
  { brand: 'Numbuzin', name: 'No.5 Goodbye Blemish Serum', category: 'serum', ingredients: 'Niacinamide, Tranexamic Acid', usageTime: 'BOTH' },
  { brand: 'Mary & May', name: 'Tranexamic Acid + Glutathione Serum', category: 'serum', ingredients: 'Tranexamic Acid, Glutathione', usageTime: 'BOTH' },
  { brand: 'Mixsoon', name: 'Bean Essence', category: 'essence', ingredients: 'Fermented extracts', usageTime: 'BOTH' },
  { brand: 'Torriden', name: 'Dive-In Serum', category: 'serum', ingredients: 'Hyaluronic Acid', usageTime: 'BOTH' },
  { brand: 'Dear, Klairs', name: 'Freshly Juiced Vitamin Drop', category: 'serum', ingredients: 'Vitamin C', usageTime: 'AM' },
  { brand: 'Benton', name: 'Snail Bee High Content Essence', category: 'essence', ingredients: 'Snail Mucin, Bee Venom', usageTime: 'BOTH' },
  { brand: 'Laneige', name: 'Cream Skin', category: 'serum', ingredients: 'Ceramides, peptides', usageTime: 'BOTH' },
  { brand: 'Vichy', name: 'Liftactiv Vitamin C Serum', category: 'serum', ingredients: 'Vitamin C', usageTime: 'AM' },
  { brand: 'Bioderma', name: 'Sébium Serum', category: 'exfoliant', ingredients: 'Salicylic Acid, Glycolic Acid', usageTime: 'PM' },
  { brand: 'Cetaphil', name: 'Gentle Clear Acne Serum', category: 'serum', ingredients: 'Salicylic Acid', usageTime: 'PM' },
  { brand: 'Neutrogena', name: 'Oil-Free Acne Wash', category: 'cleanser', ingredients: 'Salicylic Acid', usageTime: 'PM' },
  { brand: 'Nivea', name: 'Luminous630 Anti-Dark Spot Serum', category: 'serum', ingredients: 'Luminous630', usageTime: 'BOTH' },
  { brand: 'Garnier', name: 'Vitamin C Booster Serum', category: 'serum', ingredients: 'Vitamin C derivative', usageTime: 'AM' },
  { brand: 'L\'Oréal Paris', name: 'Revitalift Clinical Vitamin C', category: 'serum', ingredients: 'Vitamin C', usageTime: 'AM' },
  { brand: 'Olay', name: 'Super Serum', category: 'serum', ingredients: 'Niacinamide, Vitamin C derivatives, AHA', usageTime: 'AM' },
]

export function searchNigerianBrands(query) {
  const term = query.trim().toLowerCase()
  if (!term) return []

  const brands = new Set()
  for (const product of NIGERIAN_PRODUCTS) {
    if (product.brand.toLowerCase().includes(term)) brands.add(product.brand)
  }
  return [...brands]
}

export function searchNigerianProducts(brand, query) {
  const brandTerm = (brand || '').trim().toLowerCase()
  const nameTerm = (query || '').trim().toLowerCase()

  return NIGERIAN_PRODUCTS
    .filter((product) => {
      const brandMatch = !brandTerm || product.brand.toLowerCase().includes(brandTerm)
      const nameMatch = !nameTerm || product.name.toLowerCase().includes(nameTerm)
      return brandMatch && nameMatch
    })
    .map((product, index) => ({
      code: `ng-${index}`,
      name: product.name,
      brand: product.brand,
      category: product.category,
      ingredients: product.ingredients,
    }))
}
